# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='put_data',
        ),
        migrations.AddField(
            model_name='question',
            name='put_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='put_date'),
            preserve_default=False,
        ),
    ]
